service: vision
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  iam:
   role: 
     statements: 
      - Effect: Allow
        Action: Rekognition:*
        Resource: "*"

functions:
  health:
    handler: routes/health.health
    events:
      - httpApi:
          path: /
          method: get

  v1Description:
    handler: routes/v1/v1_description.v1_description
    events:
      - httpApi:
          path: /v1
          method: get

  v1Vision:
    handler: routes/v1/v1_vision.v1_vision
    events:
      - httpApi:
          path: /v1/vision
          method: post

  v2Description:
    handler: routes/v2/v2_description.v2_description
    events:
      - httpApi:
          path: /v2
          method: get
  v2Vision:
    handler: routes/v2/v2_vision.v2_vision
    timeout: 10
    events:
      - httpApi:
          path: /v2/vision
          method: post
#plugins:
 # - serverless-offline
